name: candlesticks_plus
description: A high-performance full featured candlesticks chart for all platforms.
version: 1.0.4
homepage: https://github.com/mhbdev/candlesticks

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
